# Start by routing the security pages!
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

authentication_login:
    pattern:  /login

authentication_register:
    pattern: /register

authentication_logout:
    pattern: /logout


# Other pages
homepage:
    pattern:  /
    defaults: { _controller: MatchTrackerAppBundle:Page:index }
    requirements:
        _method:  GET

competition_show:
    pattern: /competities/detail/{name}
    defaults: { _controller: MatchTrackerAppBundle:Competition:detail }
    requirements:
        _method:  GET

competition_maker:
    pattern: /competities/maker
    defaults: { _controller: MatchTrackerAppBundle:Competition:maker }
    requirements:
        _method:  GET|POST

competition:
    pattern: /competities/{sport}
    defaults: { _controller: MatchTrackerAppBundle:Competition:index, sport: alles }
    requirements:
        _method:  GET

dashboard:
    pattern:  /dashboard
    defaults: { _controller: MatchTrackerAppBundle:Dashboard:index }
