parameters:
#    match_tracker_app.example.class: MatchTracker\AppBundle\Example

services:
    my.facebook.user:
        class: MatchTracker\AppBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"

    my.twitter.user:
        class: MatchTracker\AppBundle\Security\User\Provider\TwitterProvider
        arguments:
            twitter_oauth: "@fos_twitter.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            session: "@session"

    matchtracker_registration_form:
        class: MatchTracker\AppBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            -  { name: form.type }