parameters:
#    match_tracker_app.example.class: MatchTracker\AppBundle\Example

services:
#    match_tracker_app.example:
#        class: %match_tracker_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
