parameters:
#    match_tracker_app.example.class: MatchTracker\AppBundle\Example

services:
#    match_tracker_app.example:
#        class: %match_tracker_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    my.facebook.user:
        class: MatchTracker\AppBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"