# Start by routing the security pages!
authentication_login:
    pattern:  /login
    defaults: { _controller: MatchTrackerBundle:Authentication:login }
    requirements:
        _method:  GET

# We don't need a controller, because the core.security event intercepts the request and handles it.
authentication_login_check:
    pattern: /login_check

authentication_login_facebook_check:
    pattern: /login_facebook_check

authentication_logout:
    pattern:  /logout


# Other pages
homepage:
    pattern:  /
    defaults: { _controller: MatchTrackerBundle:Page:index }
    requirements:
        _method:  GET

competition_show:
    pattern: /competities/detail/{name}
    defaults: { _controller: MatchTrackerBundle:Competition:detail }
    requirements:
        _method:  GET

competition:
    pattern: /competities/{sport}
    defaults: { _controller: MatchTrackerBundle:Competition:index, sport: alles }
    requirements:
        _method:  GET

authentication_register:
    pattern: /register
    defaults: { _controller: MatchTrackerBundle:Authentication:register }
    requirements:
        _method:  GET|POST

dashboard:
    pattern:  /dashboard
    defaults: { _controller: MatchTrackerBundle:Dashboard:index }
