match_tracker_homepage:
    pattern:  /
    defaults: { _controller: MatchTrackerBundle:Home:index }
    requirements:
        _method:  GET

match_tracker_competition_show:
    pattern: /competities/detail/{name}
    defaults: { _controller: MatchTrackerBundle:Competition:detail }
    requirements:
        _method:  GET

match_tracker_competition:
    pattern: /competities/{sport}
    defaults: { _controller: MatchTrackerBundle:Competition:index, sport: alles }
    requirements:
        _method:  GET

match_tracker_authentication_login:
    pattern: /login
    defaults: { _controller: MatchTrackerBundle:Authentication:login }
    requirements:
        _method:  GET

match_tracker_authentication_check:
    pattern: /login_check

match_tracker_authentication_register:
    pattern: /register
    defaults: { _controller: MatchTrackerBundle:Authentication:register }
    requirements:
        _method:  GET

match_tracker_authentication_register_check:
    pattern: /register
    defaults: { _controller: MatchTrackerBundle:Authentication:register }
    requirements:
        _method:  POST
