parameters:
#    match_tracker.example.class: MatchTracker\Bundle\Example

services:
#    match_tracker.example:
#        class: %match_tracker.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
