# Route to the matchtracker bundle
match_tracker:
    resource: "@MatchTrackerBundle/Resources/config/routing.yml"
    prefix:   /

 
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
