jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle]
        fos_userbundle:
            id: fos_user.user_provider.username_email
        my_fos_facebook_provider:
            id: my.facebook.user

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    /.*
            form_login:
                check_path: /login_check
                login_path: /login
                provider: fos_userbundle
            logout:
                path:   /logout
                target: /
                handlers: ["fos_facebook.logout_handler"]
            fos_facebook:
                app_url: "http://apps.facebook.com/matchtracker/"
                server_url: "http://matchtracker.localhost/"
                login_path: /login
                check_path: /login_facebook_check
                default_target_path: /
                provider: my_fos_facebook_provider
            security: true
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: /dashboard/.*, role: ROLE_ADMIN }
        #- { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
