jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    /.*
            form_login:
                check_path: /login_check
                login_path: /login
                provider: fos_userbundle
            logout:
                path:   /logout
                target: /
            security: true
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: /dashboard/.*, role: ROLE_ADMIN }
        #- { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
