# Other pages
homepage:
    pattern:  /
    defaults: { _controller: MatchTrackerAppBundle:Page:index }
    requirements:
        _method:  GET

competition_show:
    pattern: /competities/detail/{name}
    defaults: { _controller: MatchTrackerAppBundle:Competition:detail }
    requirements:
        _method:  GET

competition_maker:
    pattern: /competities/nieuw
    defaults: { _controller: MatchTrackerAppBundle:CompetitionMaker:index }
    requirements:
        _method:  GET|POST

competition_maker_formula:
    pattern: /competities/nieuw/formule/{formula}
    defaults: { _controller: MatchTrackerAppBundle:CompetitionMaker:formula, formula: null}
    requirements:
        _method:  GET|POST

competition_maker_sport:
    pattern: /competities/nieuw/sport/{type}
    defaults: { _controller: MatchTrackerAppBundle:CompetitionMaker:sport, type: null }

competition_maker_location:
    pattern: /competities/nieuw/locatie
    defaults: { _controller: MatchTrackerAppBundle:CompetitionMaker:location}
    requirements:
        _method:  GET|POST

competition:
    pattern: /competities/{sport}
    defaults: { _controller: MatchTrackerAppBundle:Competition:index, sport: alles }
    requirements:
        _method:  GET

dashboard:
    pattern:  /dashboard
    defaults: { _controller: MatchTrackerAppBundle:Dashboard:index }

profile:
    pattern:  /dashboard/profile
    defaults: { _controller: MatchTrackerAppBundle:Dashboard:profile }

mycompetitions:
    pattern:  /dashboard/mijncompetities
    defaults: { _controller: MatchTrackerAppBundle:Dashboard:competitions }

team:
    pattern: /team/{nameCanonical}
    defaults: { _controller: MatchTrackerAppBundle:Team:index }

teamEdit:
    pattern: /team/{nameCanonical}/edit/{code}
    defaults: { _controller: MatchTrackerAppBundle:Team:edit }





