# Homepage
homepage:
    pattern:  /
    defaults:
        _controller: MatchTrackerAppBundle:Page:index
        label: "Home"
    requirements:
        _method:  GET

# Competition maker
# Step1:
competition_maker:
    pattern: /competities/nieuw
    defaults:
        _controller: MatchTrackerAppBundle:CompetitionMaker:index
        parent: "dashboard"
        label: "Nieuwe competitie: info"
    requirements:
        _method:  GET|POST

#Step2:
competition_maker_sport:
    pattern: /competities/nieuw/sport/{type}
    defaults:
        _controller: MatchTrackerAppBundle:CompetitionMaker:sport
        type: null
        parent: "dashboard"
        label: "Nieuwe competitie: info"

# Step3:
competition_maker_formula:
    pattern: /competities/nieuw/formule/{formula}
    defaults:
        _controller: MatchTrackerAppBundle:CompetitionMaker:formula
        formula: null
        parent: "dashboard"
        label: "Nieuwe competitie: formule"
    requirements:
        _method:  GET|POST

# Step4:
competition_maker_location:
    pattern: /competities/nieuw/locatie
    defaults:
        _controller: MatchTrackerAppBundle:CompetitionMaker:location
        parent: "dashboard"
        label: "Nieuwe competitie: locatie"
    requirements:
        _method:  GET|POST

#Competities
competition:
    pattern: /competities/{sport}
    defaults:
        _controller: MatchTrackerAppBundle:Competition:index
        sport: alles
    requirements:
        _method:  GET

competition_show:
    pattern: /competities/detail/{nameCanonical}
    defaults:
        _controller: MatchTrackerAppBundle:Competition:detail
    requirements:
        _method:  GET


# Dashboard and subpages
dashboard:
    pattern:  /dashboard
    defaults:
        _controller: MatchTrackerAppBundle:Dashboard:index
        parent: "homepage"

profile:
    pattern:  /dashboard/profile
    defaults:
        _controller: MatchTrackerAppBundle:Dashboard:profile
        parent: "dashboard"
        label: "Profiel"

mycompetitions:
    pattern:  /dashboard/mijncompetities
    defaults:
        _controller: MatchTrackerAppBundle:Dashboard:competitions
        parent: "dashboard"
        label: "Mijn competities"


# Team page and editor
team:
    pattern: /team/{nameCanonical}
    defaults:
        _controller: MatchTrackerAppBundle:Team:index
        parent: "homepage"

team_edit:
    pattern: /team/{nameCanonical}/edit/{code}
    defaults:
        _controller: MatchTrackerAppBundle:Team:edit
        parent: "team"
        label: "Team bewerken"
