# Other pages
homepage:
    pattern:  /
    defaults: { _controller: MatchTrackerAppBundle:Page:index }
    requirements:
        _method:  GET

competition_show:
    pattern: /competities/detail/{name}
    defaults: { _controller: MatchTrackerAppBundle:Competition:detail }
    requirements:
        _method:  GET

competition_maker:
    pattern: /competities/maker
    defaults: { _controller: MatchTrackerAppBundle:Competition:maker }
    requirements:
        _method:  GET|POST

competition_maker_formula:
    pattern: /competities/maker/formule/{formula}
    defaults: { _controller: MatchTrackerAppBundle:Competition:makerFormula, formula: null}
    requirements:
        _method:  GET|POST

competition_maker_location:
    pattern: /competities/maker/locatie
    defaults: { _controller: MatchTrackerAppBundle:Competition:makerLocation}
    requirements:
        _method:  GET|POST

competition_maker_sport:
    pattern: /competities/maker/{sport}/{type}
    defaults: { _controller: MatchTrackerAppBundle:Competition:makerSport, sport: null, type: null }
    requirements:
        _method:  GET|POST

competition:
    pattern: /competities/{sport}
    defaults: { _controller: MatchTrackerAppBundle:Competition:index, sport: alles }
    requirements:
        _method:  GET

dashboard:
    pattern:  /dashboard
    defaults: { _controller: MatchTrackerAppBundle:Dashboard:index }

profile:
    pattern:  /dashboard/profile
    defaults: { _controller: MatchTrackerAppBundle:Dashboard:profile }

mycompetitions:
        pattern:  /dashboard/mijncompetities
        defaults: { _controller: MatchTrackerAppBundle:Dashboard:competitions }


