# Homepage
homepage:
    pattern:  /
    defaults:
        _controller: MatchTrackerAppBundle:Page:index
        label: "Home"
    requirements:
        _method:  GET

# Competition maker
# Step1:
competition_maker:
    pattern: /competities/nieuw
    defaults:
        _controller: MatchTrackerAppBundle:CompetitionMaker:index
        parent: "dashboard"
        label: "Nieuwe competitie: info"
    requirements:
        _method:  GET|POST

#Step2:
competition_maker_sport:
    pattern: /competities/nieuw/sport/{type}
    defaults:
        _controller: MatchTrackerAppBundle:CompetitionMaker:sport
        type: null
        parent: "dashboard"
        label: "Nieuwe competitie: info"

# Step3:
competition_maker_formula:
    pattern: /competities/nieuw/formule/{formula}
    defaults:
        _controller: MatchTrackerAppBundle:CompetitionMaker:formula
        formula: null
        parent: "dashboard"
        label: "Nieuwe competitie: formule"
    requirements:
        _method:  GET|POST

# Step4:
competition_maker_location:
    pattern: /competities/nieuw/locatie
    defaults:
        _controller: MatchTrackerAppBundle:CompetitionMaker:location
        parent: "dashboard"
        label: "Nieuwe competitie: locatie"
    requirements:
        _method:  GET|POST

#Competities
competition:
    pattern: /competities/{sport}
    defaults:
        _controller: MatchTrackerAppBundle:Competition:index
        sport: alles
        parent: "homepage"
        label: "Competities"

competition_show_option:
    pattern: /competities/detail/{nameCanonical}/{option}
    defaults:
        _controller: MatchTrackerAppBundle:Competition:detail
        parent: "competition"
        label: "Detail"

competition_show:
    pattern: /competities/detail/{nameCanonical}
    defaults:
        _controller: MatchTrackerAppBundle:Competition:detail
        parent: "competition"
        label: "Detail"
        option: "info"

# Dashboard and subpages
dashboard:
    pattern:  /dashboard
    defaults:
        _controller: MatchTrackerAppBundle:Dashboard:index
        parent: "homepage"

profile:
    pattern:  /dashboard/profile
    defaults:
        _controller: MatchTrackerAppBundle:Dashboard:profile
        parent: "dashboard"
        label: "Profiel"

mycompetitions:
    pattern:  /dashboard/mijncompetities
    defaults:
        _controller: MatchTrackerAppBundle:Dashboard:competitions
        parent: "dashboard"
        label: "Mijn competities"

mycompetitions_teams:
    pattern: /dashboard/mijncompetities/{nameCanonical}/teams
    defaults:
      _controller: MatchTrackerAppBundle:Dashboard:teams
      parent: "mycompetitions"
      label: "Teams"


matchSchedule_maker:
      pattern: /dashboard/mijncompetities/{nameCanonical}/schedule
      defaults:
        _controller: MatchTrackerAppBundle:Dashboard:schedule
        parent: "mycompetitions"
        label: "schedule"


mymatches:
    pattern:  /dashboard/mijnwedstrijden
    defaults:
        _controller: MatchTrackerAppBundle:Dashboard:matches
        parent: "dashboard"
        label: "Mijn wedstrijden"


# Team page and editor
team:
    pattern: /team/{nameCanonical}
    defaults:
        _controller: MatchTrackerAppBundle:Team:index
        parent: "homepage"

team_edit:
    pattern: /team/{nameCanonical}/edit/{code}
    defaults:
        _controller: MatchTrackerAppBundle:Team:edit
        parent: "team"
        label: "Team bewerken"


# MatchCenter
matchcenter:
    pattern: /matchcenter
    defaults:
        _controller: MatchTrackerAppBundle:MatchCenter:index
        parent: "homepage"
        label: "Matchcenter"

matchcenter_detail:
    pattern: /matchcenter/{id}
    defaults:
        _controller: MatchTrackerAppBundle:MatchCenter:detail
        parent: "matchcenter"
        label: "Detail"

matchcenter_report:
    pattern: /matchcenter/{id}/verslag
    defaults:
        _controller: MatchTrackerAppBundle:MatchCenter:report
        parent: "Matchcenter"
        label: "Live verslag geven"
